context: ${cluster_name}
contexts:
  ${cluster_name}:
    endpoints:
      - ${talos_endpoint}
    ca: ${ca_certificate}
    crt: ${client_certificate}
    key: ${client_key}
    auth:
      type: client-certificate
