name: Validate OpenTofu

on:
  pull_request:
    paths:
      - 'talos-template/**'
  push:
    branches:
      - main
    paths:
      - 'talos-template/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest
          
      - name: Tofu Format Check
        run: tofu fmt -check -recursive
        working-directory: talos-template
        
      - name: Tofu Init
        run: tofu init -backend=false
        working-directory: talos-template
        
      - name: Tofu Validate
        run: tofu validate
        working-directory: talos-template